### ISSUE TITLE
hello I have a problem about piano keys please can you help me quickly

### ISSUE THREAD

**Issue by deniz6900357** [Mayuresh1611/Paper-Piano#3]
![WhatsApp Image 2024-03-14 at 00 39 26](https://github.com/Mayuresh1611/Paper-Piano/assets/116761177/e51cd696-1e85-469d-9c68-89005cde253f)
![WhatsApp Image 2024-03-14 at 00 39 26 (1)](https://github.com/Mayuresh1611/Paper-Piano/assets/116761177/72a574a4-1976-432e-99a1-db2fe8091ab8)
this is my terminal:
C:\Users\bende\PycharmProjects\Paper-Piano1\.venv\Scripts\python.exe C:\Users\bende\PycharmProjects\Paper-Piano1\run.py 
2024-03-14 00:36:17.630088: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-14 00:36:19.824424: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
pygame 2.5.2 (SDL 2.28.3, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
We need to train model on your finger's data
We need to train model on your finger's data
welcome to Paper Piano
TRAINING DATA CLEARED
We need to train model on your finger's data
TRAINING DATA CLEARED
The First window is try window so that you can adjust the finger position, adjust hand position so that box will cover  finger tip and finger tip
1. Window after try will be touch train window
	 do not lift any finger, move fingers slowly on the paper to get all angles
2. After this window untouch train window will pop up
	 lift fingers so that it can take pics of finger tips for training
	 Then model will be trained and you should see the prediction window for Index finger
Press Y to move for training stage
>> y
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\run.py", line 112, in <module>
    fetch_train_data()
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\run.py", line 88, in fetch_train_data
    fetch_data.Try(FINGER) 
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\src\fetch_data.py", line 112, in Try
    results = hands.process(image)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\.venv\Lib\site-packages\mediapipe\python\solutions\hands.py", line 153, in process
    return super().process(input_data={'image': image})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\.venv\Lib\site-packages\mediapipe\python\solution_base.py", line 365, in process
    self._graph.wait_until_idle()
KeyboardInterrupt

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

**Comment by deniz6900357** [comment]
![20240314_004341.jpg](https://github.com/Mayuresh1611/Paper-Piano/assets/116761177/abfde44a-c505-49fb-b12e-51a432c4c7f7)

**Comment by Mayuresh1611** [comment]
Hey can you try changing 
``sys.path.append(src)
import fetch_data , GLOBAL , train_model, piano``

To 

``from src import fetch_data , GLOBAL , train_model, piano``

If this works for you then make a pull request.

**Comment by deniz6900357** [comment]
hello thank you but ı have a new problem like this:
C:\Users\bende\PycharmProjects\Paper-Piano1\.venv\Scripts\python.exe C:\Users\bende\PycharmProjects\Paper-Piano1\run.py 
2024-03-14 08:28:22.944743: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-14 08:28:27.695117: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\run.py", line 8, in <module>
    from src import fetch_data , GLOBAL , train_model, piano
  File "C:\Users\bende\PycharmProjects\Paper-Piano1\src\piano.py", line 5, in <module>
    from mapping import analyse, draw_over_image
ModuleNotFoundError: No module named 'mapping'

Process finished with exit code 1

**Comment by Mayuresh1611** [comment]
you are using pycharm right? wait i'll see what I can do.

**Comment by deniz6900357** [comment]
> you are using pycharm right? wait i'll see what I can do.
> 

Yeah ım using pycharm Im waitingg thank youu ı will use it for fll project in this weekend if its work

**Comment by deniz6900357** [comment]
Hellooo can you find the problem?

**Comment by Mayuresh1611** [comment]
hey sorry for being late, 
I have pushed little fixes on py-charm-compatibility branch
you can access it by running following commands 
``git fetch origin``
``git checkout py-charm-compatibility``
``git pull``

**Comment by deniz6900357** [comment]
> hey sorry for being late, 
> I have pushed little fixes on py-charm-compatibility branch
> you can access it by running following commands 
> ``git fetch origin``
> ``git checkout py-charm-compatibility``
> ``git pull``
> 
> let me know if this works, so we can merge it with main branch. Tnx!

Thankk you should ı write this commands to pycharm terminal

**Comment by Mayuresh1611** [comment]
yesss

**Comment by deniz6900357** [comment]
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
ı have git but I don't understand why pycharm didn't see it

**Comment by Mayuresh1611** [comment]
hmm, try running command prompt in the same folder

**Comment by Mayuresh1611** [comment]
worked or not?
